sudo: required
language: python
#env:
#  global:
#    - TWINE_USERNAME=Masrepus
#    - secure: GH5caMSGX5vrXn2aIP2thNELEQLz2ngArN4OqaGPuDCLx67xcrOKHy9XV75MUosyIcgCDMndBo8DVhVPBfnD2d9ZjmRSMv5yw9HdDdbpN7wVThs0rZynpjf5TlbEKTeQffVlOmbP1U4HWQIqkTn+uLpgM3QD4fWAapdlq+ag/zlL7650AeErEqUGqzKRJ6EqmCzWYLZhqDLGw599Z7H8db3cO0u1WPouOxwq+cUfo1fkazc7eeWpMNRsS7L/BVitacVCClnJqpxTMFbwjpsaqJhd6RKX8GFEedcWRyqL7Rkw67nbBJ+MtdiqRhG18aSzaMSI+Itn+uyMIUsa0HWVQjM6v3RrwON4+ggClz8iHsY0uAov6FKjmMT5HNuhat4Kdi8riRfkaFdpyC7aoM1i2x0CU1h1dYD9qgNXaK7hEcJdn+i6jF6RU5vtj+2DibKKCNHewx5RofbHvj2L5bs9nmACMfvjLBVY/NUZsjcSnm1OPyBZXgj7WWnnGAcYvj3gBomhbi5FubfaSuhmVfRqpJaILuK5M4YNcer1jJsXe3j2z9r5fx0JYC1lDuIO4skxvquLcEf5jYoHTxY91xSGfzxk0m6KbRalVa4b82UEbK17ThV1MekMD7buz7IQHRutXc7FUejeZQyqYQguHfwC1o0uBtmXqMOHFvS4P41OOD8=

matrix:
  include:
#  - name: "Python 3.7.1 on Xenial Linux"
#    python: 2.7
#    dist: xenial          # required for Python >= 3.7
#    cache: pip
#    before_install:
#      - sudo apt update
#      - sudo apt install python3 python3-pip
#    env: DISTS="sdist3 bdist3"
#  - name: Python 3.7.2 on macOS
#    os: osx
#    osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
#    language: shell       # 'language: python' is an error on Travis CI macOS
#    env: DISTS="bdist3"
  - name: Windows
    os: windows           # Windows 10.0.17134 N/A Build 17134
    language: shell       # 'language: python' is an error on Travis CI Windows
    before_install: choco install python2 python3 make
    env: PATH=/c/Python27/:/c/Python27/Scripts:/c/Python37:/c/Python37/Scripts:$PATH MAKE_OPTS="cross-win64" DISTS="bdist3"

install:
        - pip3 install --upgrade --user pip setuptools pytest wheel twine

script:
- ./make.sh $MAKE_OPTS

before_deploy: cd bindings/python
deploy:
      provider: script
      script: make $DISTS
      skip_cleanup: true
      on:
        #tags: true
        all_branches: true